#!/bin/sh

bspc monitor DisplayPort-0 -d 1 2 3 4 5 6 7
bspc monitor HDMI-A-0 -d A B C D E F G

bspc config active_border_color		  $EDDE_CLR_WINDOW
bspc config automatic_scheme        longest_side
bspc config borderless_monocle		  true
bspc config border_width            $EDDE_BORDER
bspc config external_rules_command	external-rules
bspc config focus_follows_pointer	  false
bspc config focused_border_color	  $EDDE_CLR_FOCUS
bspc config gapless_monocle			    true
bspc config normal_border_color		  $EDDE_CLR_BORDER
bspc config presel_feedback_color   $EDDE_CLR_BORDER
bspc config single_monocle			    true
bspc config split_ratio				      0.5
bspc config swallow_first_click		  true

set-gap $EDDE_GAP

bspc rule -a Lutris desktop=^2
bspc rule -a Steam desktop=^2 follow=off
bspc rule -a battle.net.exe desktop=^2
bspc rule -a discord desktop=^3 follow=off
bspc rule -a TelegramDesktop desktop=^3
bspc rule -a dota2 desktop=^4
bspc rule -a gw2-64.exe desktop=^4
bspc rule -a PortalWars-Linux-Shipping desktop=^4 follow=on
bspc rule -a easyeffects state=floating
bspc rule -a Font-manager state=floating
bspc rule -a Gcolor3 state=floating sticky=on
bspc rule -a gnome-calculator state=floating sticky=on
bspc rule -a obs state=floating sticky=on
bspc rule -a Gnome-disks state=floating
bspc rule -a Gpicview state=floating
bspc rule -a Libfm-pref-apps state=floating
bspc rule -a Lxappearance state=floating
bspc rule -a Lxtask state=floating sticky=on
bspc rule -a Pavucontrol state=floating
bspc rule -a Godot_ProjectList:Godot state=floating sticky=on

event-handler &
show-wallpaper -d
# steam &
# thunar --daemon &
