#!/bin/bash
#
# often-used monitor and speaker settings
#
# usage: set-output -a [DEVICE] -e [true|false] -u [true|false]
# -a: set default audio device
# -e: enable external monitor
# -u: ultrawide resolution (disable for recording in 1920x1080)

A=''
E=''
U=''
while getopts ':a:e:u:' opt; do
  case "${opt}" in
    a) A="${OPTARG}";;
    e) E="${OPTARG}";;
    u) U="${OPTARG}";;
  esac
done

# audio device
if [ "$A" != "" ]; then
  newSink=$(pactl list short sinks | grep $A | cut -f1)
  if [ -n "$newSink" ]; then
    pactl list short sink-inputs|while read stream; do
      streamId=$(echo $stream|cut '-d ' -f1)
      pactl move-sink-input "$streamId" "$newSink"
      pactl set-default-sink $newSink
    done
  fi
fi

XRANDR=''

# external monitor
if [ "$E" = "true" ]; then
  XRANDR+=' --output HDMI-A-0 --auto --mode 1920x1080 --left-of DisplayPort-0'
  eww update externalMonitor=true
  notify "enable external"
elif [ "$E" = "false" ]; then
  XRANDR+=' --output HDMI-A-0 --off'
  # echo pow 0 | cec-client -s -d 1
  eww update externalMonitor=false
  notify "disable external"
fi

# ultrawide resolution
if [ "$U" = "false" ]; then
  XRANDR+=' --output DisplayPort-0 --mode 1920x1080'
  eww update ultrawide=false
  notify "disable ultrawide"
elif [ "$U" = "true" ]; then
  XRANDR+=' --output DisplayPort-0 --mode 2560x1080'
  eww update ultrawide=true
  notify "enable ultrawide"
fi

[ "$XRANDR" != "" ] && xrandr $XRANDR
