# ~/.zshrc

# aliases
[ -f ~/system/zsh/aliases ] && source ~/system/zsh/aliases

# autocompletion
autoload -Uz compinit && compinit
autoload -Uz bashcompinit && bashcompinit

# prompt
eval "$(starship init zsh)"
